# Generated by Django 2.2.28 on 2022-05-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190629_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tenant',
            field=models.TextField(default='shared', verbose_name='tenant'),
        ),
    ]
